name: pass_flutter
version: 2.0.2
description: A Flutter library for getting and reading Apple Wallet passes.
homepage: https://github.com/alexeynobody/pass-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.3.7
  dio: ^5.3.2
  path_provider: ^2.1.0
  uuid: ^3.0.7
  path: ^1.8.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  json_serializable: ^6.7.1
